name: aqark_futter_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2+1
  path: ^1.9.1
  firebase_auth: ^6.4.0
  firebase_core: ^4.7.0
  google_sign_in: ^7.2.0
  connectivity_plus: ^7.1.1
  firebase_database: ^12.3.0
  shared_preferences: ^2.5.5
  firebase_data_connect: ^0.3.0
  get_it: ^9.2.1
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Aqark.png"
  # Add these two lines for modern Android Adaptive Icons:
  adaptive_icon_background: "#FFFFFF" # Set this to your desired background color (White)
  adaptive_icon_foreground: "assets/images/Aqark.png" # Use the cropped image
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/properties/apartment/
    - assets/images/properties/duplex/
    - assets/images/properties/villa/
    - assets/images/properties/townhouse/
    - assets/images/properties/studio/
    - assets/images/properties/penthouse/
