// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKvOowOFtRKrxK_J1p3re1qEPnYoZPhWk',
    appId: '1:830265072894:web:94ec557d32218f7a8299af',
    messagingSenderId: '830265072894',
    projectId: 'aqark-real-estate-app',
    authDomain: 'aqark-real-estate-app.firebaseapp.com',
    databaseURL: 'https://aqark-real-estate-app-default-rtdb.firebaseio.com',
    storageBucket: 'aqark-real-estate-app.firebasestorage.app',
    measurementId: 'G-V41FK9RMDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNrRMQ7QnZI5Ko8ljQyt18N2Qrkk80Ohw',
    appId: '1:830265072894:android:4db6b8b2227c1d2a8299af',
    messagingSenderId: '830265072894',
    projectId: 'aqark-real-estate-app',
    databaseURL: 'https://aqark-real-estate-app-default-rtdb.firebaseio.com',
    storageBucket: 'aqark-real-estate-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM231PDo3QFqYBwhE_RtATX5KVLhAfbtw',
    appId: '1:830265072894:ios:d7de5b9809a6bbd88299af',
    messagingSenderId: '830265072894',
    projectId: 'aqark-real-estate-app',
    databaseURL: 'https://aqark-real-estate-app-default-rtdb.firebaseio.com',
    storageBucket: 'aqark-real-estate-app.firebasestorage.app',
    iosClientId:
        '830265072894-5jpgsf27g0lpjv7b38qr9qhuif42qtt6.apps.googleusercontent.com',
    iosBundleId: 'com.example.aqarkFutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM231PDo3QFqYBwhE_RtATX5KVLhAfbtw',
    appId: '1:830265072894:ios:d7de5b9809a6bbd88299af',
    messagingSenderId: '830265072894',
    projectId: 'aqark-real-estate-app',
    databaseURL: 'https://aqark-real-estate-app-default-rtdb.firebaseio.com',
    storageBucket: 'aqark-real-estate-app.firebasestorage.app',
    iosClientId:
        '830265072894-5jpgsf27g0lpjv7b38qr9qhuif42qtt6.apps.googleusercontent.com',
    iosBundleId: 'com.example.aqarkFutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKvOowOFtRKrxK_J1p3re1qEPnYoZPhWk',
    appId: '1:830265072894:web:14eea6b6015280ee8299af',
    messagingSenderId: '830265072894',
    projectId: 'aqark-real-estate-app',
    authDomain: 'aqark-real-estate-app.firebaseapp.com',
    databaseURL: 'https://aqark-real-estate-app-default-rtdb.firebaseio.com',
    storageBucket: 'aqark-real-estate-app.firebasestorage.app',
    measurementId: 'G-R7E9PH3V0M',
  );
}
